<?php
/**
 * PAYONE Magento 2 Connector is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * PAYONE Magento 2 Connector is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with PAYONE Magento 2 Connector. If not, see <http://www.gnu.org/licenses/>.
 *
 * PHP version 5
 *
 * @category  Payone
 * @package   Payone_Magento2_Plugin
 * @author    FATCHIP GmbH <support@fatchip.de>
 * @copyright 2003 - 2016 Payone GmbH
 * @license   <http://www.gnu.org/licenses/> GNU Lesser General Public License
 * @link      http://www.payone.de
 */

$oTransactionStatus = $block->getTransactionStatusEntry();
?>
<?php if (!$oTransactionStatus): ?>
    <?php echo __('TransactionStatus entry could not be found!'); ?>
<?php else: ?>
    <div data-mage-init='{"floatingHeader": {}}' class="page-actions"><?php echo $block->getButtonsHtml() ?></div>
    <section class="admin__page-section">
        <div class="admin__page-section-content">
            <div class="admin__page-section-item">
                <div class="admin__page-section-item-title">
                    <span class="title"><?php echo __('TransactionStatus'); ?></span>
                </div>
                <div class="admin__page-section-item-content">
                    <table class="admin__table-secondary">
                        <tbody>
                            <?php foreach ($oTransactionStatus->getRawStatusArray() as $sKey => $mValue): ?>
                            <tr>
                                <th><?php echo $sKey; ?></th>
                                <td>
                                    <?php 
                                        if (!is_array($mValue)) { 
                                            echo $mValue; 
                                        } elseif (count($mValue) > 0) { 
                                            $blFirst = true;
                                            foreach ($mValue as $sSubKey => $sSubValue) {
                                                if (!empty($sSubValue)) {
                                                    if (!$blFirst) echo ', ';
                                                    echo $sSubValue;
                                                    $blFirst = false;
                                                }
                                            }
                                        }
                                    ?>
                                </td>
                            </tr>                
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
<?php endif; ?>
