<?php
/**
 * PAYONE Magento 2 Connector is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * PAYONE Magento 2 Connector is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with PAYONE Magento 2 Connector. If not, see <http://www.gnu.org/licenses/>.
 *
 * PHP version 5
 *
 * @category  Payone
 * @package   Payone_Magento2_Plugin
 * @author    FATCHIP GmbH <support@fatchip.de>
 * @copyright 2003 - 2016 Payone GmbH
 * @license   <http://www.gnu.org/licenses/> GNU Lesser General Public License
 * @link      http://www.payone.de
 */

/** @var \Payone\Core\Block\RedirectReturn $block */

if ($block->isRedirectCancellation()) {
    $script = "
    require([
        'Magento_Customer/js/customer-data',
        'Magento_Checkout/js/checkout-data'
    ], function (customerData, checkoutData) {
        function redirectCancellation(customerData, checkoutData) {
            customerData.invalidate(['cart', 'checkout-data']); ";

    $oShippingAddress = $block->getShippingAddress();
    if ($block->isGuest() && $oShippingAddress && $oShippingAddress->getFirstname() && $oShippingAddress->getLastname()) {
        $script .= "
                var shippingAddressData = {
                    'company': '".$block->escapeJs($oShippingAddress->getCompany())."',
                    'telephone' : '".$block->escapeJs($oShippingAddress->getTelephone())."',
                    'firstname' : '".$block->escapeJs($oShippingAddress->getFirstname())."',
                    'lastname' : '".$block->escapeJs($oShippingAddress->getLastname())."',
                    'street' : {
                        0 : '".$block->escapeJs($oShippingAddress->getStreet()[0])."',
                        1 : '".(isset($oShippingAddress->getStreet()[1]) ? $block->escapeJs($oShippingAddress->getStreet()[1]) : '')."'
                    },
                    'city' : '".$block->escapeJs($oShippingAddress->getCity())."',
                    'country_id' : '".$block->escapeJs($oShippingAddress->getCountryId())."',
                    'postcode' : '".$block->escapeJs($oShippingAddress->getPostcode())."'
                }; ";
        if ($oShippingAddress->getRegionCode() && $oShippingAddress->getRegionId()) {
            $script .= "
                shippingAddressData.region = '".$block->escapeJs($oShippingAddress->getRegionCode())."';
                shippingAddressData.region_id = '".$block->escapeJs($oShippingAddress->getRegionId())."'; ";
        }
        $script .= "
                checkoutData.setShippingAddressFromData(shippingAddressData);
                checkoutData.setSelectedShippingRate('".$oShippingAddress->getShippingMethod()."');
                checkoutData.setInputFieldEmailValue('".$oShippingAddress->getEmail()."');
                checkoutData.setValidatedEmailValue('".$oShippingAddress->getEmail()."'); ";

        $oQuotePayment = $block->getQuotePayment();
        if ($oQuotePayment) {
            $script .= " checkoutData.setSelectedPaymentMethod('".$oQuotePayment->getMethod()."'); ";
        }
    }

    $script .= "
            }
            
            if (typeof customerData.getInitCustomerData === 'function') { // finish customerData initialization first if possible
                customerData.getInitCustomerData().done(function () {
                    redirectCancellation(customerData, checkoutData);
                });
            } else { // old functionality as fallback
                redirectCancellation(customerData, checkoutData);
            }
        });";
    echo $block->getScriptHelper()->insertScript($script);
}
