<?php

/**
 * PAYONE Magento 2 Connector is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * PAYONE Magento 2 Connector is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with PAYONE Magento 2 Connector. If not, see <http://www.gnu.org/licenses/>.
 *
 * PHP version 5
 *
 * @category  Payone
 * @package   Payone_Magento2_Plugin
 * @author    FATCHIP GmbH <support@fatchip.de>
 * @copyright 2003 - 2017 Payone GmbH
 * @license   <http://www.gnu.org/licenses/> GNU Lesser General Public License
 * @link      http://www.payone.de
 */

/**
 * @see \Payone\Core\Block\Adminhtml\Config\Form\Field\AmazonConfiguration
 */
?>
<script>
    require(['prototype'], function(){

//<![CDATA[
        function getConfiguration() {
            var elemClientId = $('payone_payment_payone_amazonpay_client_id');
            var elemSellerId = $('payone_payment_payone_amazonpay_seller_id');

            new Ajax.Request('<?php echo $block->getAjaxUrl() ?>', {
                onSuccess: function(response) {
                    try {
                        if (response.responseText != 'false' && response.responseText.isJSON()) {
                            response = response.responseText.evalJSON();
                            if (response.success == true) {
                                elemClientId.value = response.client_id;
                                elemSellerId.value = response.seller_id;
                            } else {
                                alert(response.errormessage);
                            }
                        } else {
                            alert('<?php echo __('An unknown error occured'); ?>');
                        }
                    } catch (e) {
                        alert('<?php echo __('An unknown error occured'); ?>');
                    }
                }
            });
        }

        window.getConfiguration = getConfiguration;
//]]>

    });
</script>
<div class="actions actions-validate-vat">
    <div id="validation_result" class="message-validation hidden"></div>
    <button onclick="javascript:getConfiguration(); return false;" class="action-validate-vat" type="button" id="<?php echo $block->getHtmlId() ?>">
        <span><?php echo $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>
