<?php

/**
 * PAYONE Magento 2 Connector is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * PAYONE Magento 2 Connector is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with PAYONE Magento 2 Connector. If not, see <http://www.gnu.org/licenses/>.
 *
 * PHP version 5
 *
 * @category  Payone
 * @package   Payone_Magento2_Plugin
 * @author    FATCHIP GmbH <support@fatchip.de>
 * @copyright 2003 - 2020 Payone GmbH
 * @license   <http://www.gnu.org/licenses/> GNU Lesser General Public License
 * @link      http://www.payone.de
 */

/**
 * @see \Payone\Core\Block\Adminhtml\Config\Form\Field\RefreshRatepayProfiles
 */
?>
<script>
    require(['prototype'], function(){

//<![CDATA[
        function <?php echo $block->getJavascriptFunctionName(); ?>() {
            new Ajax.Request('<?php echo $block->getAjaxUrl() ?>', {
                onSuccess: function(response) {
                    try {
                        if (response.responseText != 'false' && response.responseText.isJSON()) {
                            response = response.responseText.evalJSON();
                            if (response.success == true) {
                                location.reload();
                            } else {
                                alert(response.errormessage);
                            }
                        } else {
                            alert('<?php echo __('An unknown error occured.'); ?>');
                        }
                    } catch (e) {
                        alert('<?php echo __('An unknown exception was thrown.'); ?>');
                    }
                }
            });
        }

        window.<?php echo $block->getJavascriptFunctionName(); ?> = <?php echo $block->getJavascriptFunctionName(); ?>;
//]]>

    });
</script>
<div class="actions actions-validate-vat">
    <div id="validation_result" class="message-validation hidden"></div>
    <button onclick="javascript:<?php echo $block->getJavascriptFunctionName(); ?>(); return false;" class="action-validate-vat" type="button">
        <span><?php echo $block->escapeHtml(__('Refresh Ratepay Shop-IDs')) ?></span>
    </button>
</div>
