<?php
/**
 * PAYONE Magento 2 Connector is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * PAYONE Magento 2 Connector is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with PAYONE Magento 2 Connector. If not, see <http://www.gnu.org/licenses/>.
 *
 * PHP version 5
 *
 * @category  Payone
 * @package   Payone_Magento2_Plugin
 * @author    FATCHIP GmbH <support@fatchip.de>
 * @copyright 2003 - 2017 Payone GmbH
 * @license   <http://www.gnu.org/licenses/> GNU Lesser General Public License
 * @link      http://www.payone.de
 */
?>
<div class="amazonpay" style="text-align: center;margin-top:15px;">
    <div id="LoginWithAmazon"></div>
</div>

<script>
    window.onAmazonLoginReady = function() {
        amazon.Login.setClientId('amzn1.application-oa2-client.718254e0e9a4492f8c8efe39d2b3d187');
    };
    window.onAmazonPaymentsReady = function(){
        var authRequest;
        OffAmazonPayments.Button('LoginWithAmazon', 'A1GNVABPMV8MYX', {
            type: 'PwA',
            color: 'Gold',
            size: 'medium',
            language: 'de-DE',
            authorization: function() {
                var loginOptions = {scope: 'profile payments:widget payments:shipping_address payments:billing_address', popup: true};
                authRequest = amazon.Login.authorize (loginOptions, 'http://todo.com');
            }
        });
    }
</script>

<!-- URL changes to https://static-eu.payments-amazon.com/OffAmazonPayments/eur/lpa/js/Widgets.js when mode=live -->
<script src="https://static-eu.payments-amazon.com/OffAmazonPayments/eur/sandbox/lpa/js/Widgets.js" async="async"></script>
