<?php
/**
 * PAYONE Magento 2 Connector is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * PAYONE Magento 2 Connector is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with PAYONE Magento 2 Connector. If not, see <http://www.gnu.org/licenses/>.
 *
 * PHP version 5
 *
 * @category  Payone
 * @package   Payone_Magento2_Plugin
 * @author    FATCHIP GmbH <support@fatchip.de>
 * @copyright 2003 - 2016 Payone GmbH
 * @license   <http://www.gnu.org/licenses/> GNU Lesser General Public License
 * @link      http://www.payone.de
 */
?>

<script>
    window.onAmazonLoginReady = function() {
        amazon.Login.setClientId('<?php echo $this->getClientId(); ?>');
    };

    window.onAmazonPaymentsReady = function() {
        initializeAmazonPayButton('LoginWithAmazon1');
        if (document.getElementById('LoginWithAmazon2') !== null) {
            initializeAmazonPayButton('LoginWithAmazon2');
        }
        if (document.getElementById('LoginWithAmazon3') !== null) {
            initializeAmazonPayButton('LoginWithAmazon3');
        }
    };

    function initializeAmazonPayButton(sElementId) {
        OffAmazonPayments.Button(sElementId, '<?php echo $this->getSellerId(); ?>', {
            type: '<?php echo $this->getButtonType(); ?>',
            color: '<?php echo $this->getButtonColor(); ?>',
            language: '<?php echo $this->getButtonLanguage(); ?>',
            size: 'medium',
            authorization: function() {
                var loginOptions = {scope: 'profile payments:widget payments:shipping_address payments:billing_address', popup: true};
                var authRequest = amazon.Login.authorize (loginOptions, '<?php echo $this->getRedirectUrl(); ?>');
            }
        });
    }

    function checkForMiniBasketExistance() {
        if (document.getElementById('LoginWithAmazon1') === null) {
            setTimeout(function(){
                window.requestAnimationFrame(checkForMiniBasketExistance);
            }, 1000);
        } else {
            require(['jquery'], function($){
                $.getScript("<?php echo $this->getWidgetUrl(); ?>");
            });
        }
    }

    checkForMiniBasketExistance();
</script>