<?php
/**
 * PAYONE Magento 2 Connector is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * PAYONE Magento 2 Connector is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with PAYONE Magento 2 Connector. If not, see <http://www.gnu.org/licenses/>.
 *
 * PHP version 5
 *
 * @category  Payone
 * @package   Payone_Magento2_Plugin
 * @author    FATCHIP GmbH <support@fatchip.de>
 * @copyright 2003 - 2017 Payone GmbH
 * @license   <http://www.gnu.org/licenses/> GNU Lesser General Public License
 * @link      http://www.payone.de
 */

/**
 * @var \Payone\Core\Block\Onepage\Amazon $block
 */
?>

<script>
    window.onAmazonLoginReady = function() {amazon.Login.setClientId('<?php echo $this->getClientId(); ?>'); };
    window.onAmazonPaymentsReady = function() {
        new OffAmazonPayments.Widgets.AddressBook({
            sellerId: '<?php echo $this->getSellerId(); ?>',
            scope: 'payments:billing_address payments:shipping_address payments:widget profile',
            onAddressSelect: function(orderReference) {
                jQuery('#confirmSelection').attr('disabled', true);
            },
            design: {
                designMode: 'responsive'
            },
            onOrderReferenceCreate: function(orderReference) {
                orderReference.getAmazonOrderReferenceId();
            },
            onReady: window.onAmazonWidgetsInitialized,
            onError: window.onAmazonPaymentsError
        }).bind("addressBookWidgetDiv");

        new OffAmazonPayments.Widgets.Wallet({
            sellerId: '<?php echo $this->getSellerId(); ?>',
            scope: 'payments:billing_address payments:shipping_address payments:widget profile',
            onPaymentSelect: function(orderReference) {
                jQuery('#confirmSelection').attr('disabled', false);
            },
            design: {
                designMode: 'responsive'
            },
            onError: function (error) {
                console.log(error.getErrorCode() + ': ' + error.getErrorMessage());
            }
        }).bind("walletWidgetDiv");
    };
    window.onAmazonPaymentsError = function (error) {
        if (error.getErrorCode() === 'BuyerSessionExpired') {
            jQuery('#addressBookWidgetCover, #walletWidgetCover')
                .css('background', 'lightgrey').addClass('show').delay(15)
                .promise().done(function () {
                alert('Expired');
                //window.location.href = 'http://localhost';
            });
        } else {
            console.log(error.getErrorCode() + ': ' + error.getErrorMessage());
        }
    };
    window.onAmazonWidgetsInitialized = function (orderReference) {
        var match,
            pl     = /\+/g,
            search = /([^&=]+)=?([^&]*)/g,
            decode = function (s) { return decodeURIComponent(s.replace(pl, " ")); },
            query  = window.location.search.substring(1);

        while (match = search.exec(query)) {
            if (decode(match[1]) === "access_token") {
                window.addressConsentToken = decode(match[2]);
            }
        }
        window.amazonOrderReferenceId = orderReference.getAmazonOrderReferenceId();
    };
</script>

<div class="step" id="checkoutStepInitContent">
    <div>
        <label id="amazonWidgetsNotice">
            <?php echo __('Notice: Please verify your payment information or choose another method.') ?>
            <span></span>
        </label>
    </div>
    <div id="addressBookWidgetWrap">
        <div id="addressBookWidgetCover"></div>
        <div id="addressBookWidgetDiv"></div>
    </div>
    <div id="walletWidgetWrap">
        <div id="walletWidgetCover"></div>
        <div id="walletWidgetDiv"></div>
    </div>
</div>

<br><br>
<a href="#" class="action create primary" onclick="payoneBlub()">
    <span>Fortfahren</span>
</a>

<script src="https://static-eu.payments-amazon.com/OffAmazonPayments/eur/sandbox/lpa/js/Widgets.js" async="async"></script>

<script>
    require([
        'jquery',
        'mage/storage',
    ], function($, storage){
        var request = {
            silber: 'fisch'
        };
        window.payoneBlub = function() {

            var serviceUrl = 'https://192.168.2.194/magento213/rest/default/V1/carts/mine/payone-amazonPay';
            return storage.post(
                serviceUrl,
                JSON.stringify(request)
            ).done(
                function (response) {
                    alert('Floetenteich');
                }
            ).fail(
                function (response) {
                    alert('An error occured.');
                }
            );
        }

    });
</script>