<?php
/**
 * PAYONE Magento 2 Connector is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * PAYONE Magento 2 Connector is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with PAYONE Magento 2 Connector. If not, see <http://www.gnu.org/licenses/>.
 *
 * PHP version 5
 *
 * @category  Payone
 * @package   Payone_Magento2_Plugin
 * @author    FATCHIP GmbH <support@fatchip.de>
 * @copyright 2003 - 2016 Payone GmbH
 * @license   <http://www.gnu.org/licenses/> GNU Lesser General Public License
 * @link      http://www.payone.de
 */
?>
<br>
<?php if ($this->showMandateLink()): ?>
    <a target="_blank" class="link" href="<?php echo $this->getMandateDownloadUrl(); ?>">
        <?php echo __('Your mandate as PDF'); ?>
    </a>
<?php elseif ($this->getInstructionNotes()): ?>
    <?php echo $this->getInstructionNotes(); ?>
<?php elseif ($this->showAmazonPendingMessage()): ?>
    <div class="messages">
        <div class="message message-error notice">
            <div><?php echo __('Your transaction with Amazon Pay is currently being validated. Please be aware that we will inform you shortly as needed.'); ?></div>
        </div>
    </div>
<?php endif; ?>
