<?php
/**
 * PAYONE Magento 2 Connector is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * PAYONE Magento 2 Connector is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with PAYONE Magento 2 Connector. If not, see <http://www.gnu.org/licenses/>.
 *
 * PHP version 5
 *
 * @category  Payone
 * @package   Payone_Magento2_Plugin
 * @author    FATCHIP GmbH <support@fatchip.de>
 * @copyright 2003 - 2017 Payone GmbH
 * @license   <http://www.gnu.org/licenses/> GNU Lesser General Public License
 * @link      http://www.payone.de
 */

/**
 * @var \Payone\Core\Block\Onepage\Review\Details $block
 */
?>
<div id="details-reload" class="table-wrapper order-items cart">
    <table id="details-table" class="cart items data table table-paypal-review-items">
        <caption class="table-caption"><?php echo $block->escapeHtml(__('Items in Your Shopping Cart')); ?></caption>
        <thead>
            <tr>
                <th class="col name" scope="col"><?php echo $block->escapeHtml(__('Item')); ?></th>
                <th class="col price" scope="col"><?php echo $block->escapeHtml(__('Price')); ?></th>
                <th class="col qty" scope="col"><?php echo $block->escapeHtml(__('Qty')); ?></th>
                <th class="col subtotal" scope="col"><?php echo $block->escapeHtml(__('Subtotal')); ?></th>
            </tr>
        </thead>
        <?php foreach ($block->getItems() as $item): ?>
            <?php echo $block->getItemHtml($item) ?>
        <?php endforeach ?>
        <tfoot class="opc-block-summary">
            <?php echo $block->getChildHtml('totals'); ?>
        </tfoot>
    </table>
</div>
