<?php
/**
 * PAYONE Magento 2 Connector is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * PAYONE Magento 2 Connector is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with PAYONE Magento 2 Connector. If not, see <http://www.gnu.org/licenses/>.
 *
 * PHP version 5
 *
 * @category  Payone
 * @package   Payone_Magento2_Plugin
 * @author    FATCHIP GmbH <support@fatchip.de>
 * @copyright 2003 - 2024 Payone GmbH
 * @license   <http://www.gnu.org/licenses/> GNU Lesser General Public License
 * @link      http://www.payone.de
 */

/** @var Payone\Core\Block\Adminhtml\Order\View\SubstituteWarning $block */
?>
<div style="background-color:#fffbbb; padding: 1rem;margin-bottom: 1rem;color: #676056;">
    <?php if ($block->hasSubstituteOrder()): ?>
        <?php echo __('This order has been canceled by a safety mechanism.'); ?><br>
        <?php echo __('It has still been payed after cancellation. So a new substitute order has been created here: '); ?>
        <a href="<?php echo $block->getSubstituteOrderBackendUrl(); ?>"><?php echo $block->getSubstituteOrderIncrementNr(); ?></a>
    <?php elseif ($block->isSubstituteOrder() === true): ?>
        <?php echo __('This is a substitute order for: '); ?>
        <a href="<?php echo $block->getOrigOrderBackendUrl(); ?>"><?php echo $block->getOrder()->getPayoneCancelSubstituteIncrementId(); ?></a>
    <?php endif; ?>
</div>